/**
 * Reusable validation method catalog.
 *
 * The catalog is intentionally application-owned rather than user-entered:
 * every experiment references a stable method key, and the server verifies
 * that key before persisting an experiment plan.
 */
export const validationMethods = [
  {
    key: "user-interviews",
    name: "Customer Interviews",
    category: "generative",
    summary: "Structured conversations that uncover needs, language, and decision context.",
    bestFor: "Understanding a problem before committing to a solution.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 10,
  },
  {
    key: "problem-interviews",
    name: "Problem Interviews",
    category: "generative",
    summary: "Focused conversations about a customer's current problem, workflow, and alternatives.",
    bestFor: "Testing whether a problem is real, frequent, and painful.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 10,
  },
  {
    key: "jtbd-interviews",
    name: "JTBD Interviews",
    category: "generative",
    summary: "Contextual interviews focused on the job a customer is trying to accomplish.",
    bestFor: "Understanding switching context, desired outcomes, and decision forces.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 14,
  },
  {
    key: "survey",
    name: "Survey",
    category: "quantitative",
    summary: "Collect structured responses from a defined audience at scale.",
    bestFor: "Sizing interest or comparing preferences across segments.",
    effort: "Low",
    evidenceStrength: "Directional",
    defaultDurationDays: 7,
  },
  {
    key: "concept-testing",
    name: "Concept Testing",
    category: "evaluative",
    summary: "Show a concept and gather reactions before investing in a complete solution.",
    bestFor: "Testing comprehension, appeal, and perceived value early.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 7,
  },
  {
    key: "fake-door-test",
    name: "Fake Door Test",
    category: "smoke_test",
    summary: "Offer a clear entry point to learn whether people attempt to use a proposed capability.",
    bestFor: "Testing demand for a feature before committing engineering effort.",
    effort: "Low",
    evidenceStrength: "Directional",
    defaultDurationDays: 14,
  },
  {
    key: "landing-page-test",
    name: "Landing Page Test",
    category: "smoke_test",
    summary: "Test message and demand with a focused proposition before building.",
    bestFor: "Measuring early interest in a new concept or value proposition.",
    effort: "Low",
    evidenceStrength: "Directional",
    defaultDurationDays: 10,
  },
  {
    key: "smoke-test",
    name: "Smoke Test",
    category: "smoke_test",
    summary: "Use a lightweight signal such as a click, signup, or request to test initial demand.",
    bestFor: "Getting a fast directional read before building a full experience.",
    effort: "Low",
    evidenceStrength: "Directional",
    defaultDurationDays: 7,
  },
  {
    key: "waitlist",
    name: "Waitlist",
    category: "smoke_test",
    summary: "Invite interested people to register for a future product or capability.",
    bestFor: "Measuring explicit interest and building an early audience.",
    effort: "Low",
    evidenceStrength: "Directional",
    defaultDurationDays: 14,
  },
  {
    key: "ad-campaign",
    name: "Ad Campaign",
    category: "quantitative",
    summary: "Use targeted messaging and measured responses to test demand from a defined audience.",
    bestFor: "Comparing positioning and reaching prospective customers quickly.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 14,
  },
  {
    key: "prototype-test",
    name: "Prototype Testing",
    category: "evaluative",
    summary: "Observe people completing realistic tasks with a concept or prototype.",
    bestFor: "Testing usability and solution fit before implementation.",
    effort: "Medium",
    evidenceStrength: "Strong",
    defaultDurationDays: 7,
  },
  {
    key: "usability-test",
    name: "Usability Testing",
    category: "evaluative",
    summary: "Evaluate where participants succeed, hesitate, or fail in a workflow.",
    bestFor: "Reducing interaction risk in an existing or proposed experience.",
    effort: "Medium",
    evidenceStrength: "Strong",
    defaultDurationDays: 7,
  },
  {
    key: "concierge-mvp",
    name: "Concierge MVP",
    category: "evaluative",
    summary: "Deliver the outcome manually to learn whether the value is worth repeating.",
    bestFor: "Testing whether a service solves a meaningful customer problem.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 14,
  },
  {
    key: "wizard-of-oz",
    name: "Wizard of Oz",
    category: "evaluative",
    summary: "Present a product-like experience while a person performs the underlying work.",
    bestFor: "Testing perceived solution value before automating the implementation.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 14,
  },
  {
    key: "mvp-validation",
    name: "MVP Validation",
    category: "evaluative",
    summary: "Test a narrow working version of a product with a defined target audience.",
    bestFor: "Learning whether a minimum solution delivers meaningful value.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 30,
  },
  {
    key: "ab-test",
    name: "A/B Testing",
    category: "quantitative",
    summary: "Compare two experiences against one pre-defined behavioral measure.",
    bestFor: "Choosing between alternatives with enough eligible traffic.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 21,
  },
  {
    key: "multivariate-testing",
    name: "Multivariate Testing",
    category: "quantitative",
    summary: "Test combinations of multiple experience variables against a defined outcome.",
    bestFor: "Understanding interaction effects when traffic supports multiple variants.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 28,
  },
  {
    key: "feature-flag-experiment",
    name: "Feature Flag Experiment",
    category: "quantitative",
    summary: "Release a capability to a controlled audience and compare behavior or outcomes.",
    bestFor: "Validating an implemented feature with gradual, measurable exposure.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 21,
  },
  {
    key: "cohort-experiment",
    name: "Cohort Experiment",
    category: "quantitative",
    summary: "Compare behavior or outcomes across defined customer cohorts over time.",
    bestFor: "Understanding retention, adoption, or value differences between groups.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 30,
  },
  {
    key: "pricing-experiment",
    name: "Pricing Experiment",
    category: "quantitative",
    summary: "Test pricing or packaging options against a pre-defined response measure.",
    bestFor: "Learning how price and packaging affect demand or conversion.",
    effort: "Medium",
    evidenceStrength: "Strong",
    defaultDurationDays: 21,
  },
  {
    key: "willingness-to-pay-test",
    name: "Willingness-to-Pay Test",
    category: "quantitative",
    summary: "Ask or observe what customers would commit to paying for a proposed value.",
    bestFor: "Exploring perceived value and an initial price range.",
    effort: "Medium",
    evidenceStrength: "Directional",
    defaultDurationDays: 14,
  },
  {
    key: "beta-program",
    name: "Beta Program",
    category: "evaluative",
    summary: "Invite a selected group to use an early product and provide structured feedback.",
    bestFor: "Testing solution value and readiness with real usage.",
    effort: "High",
    evidenceStrength: "Strong",
    defaultDurationDays: 30,
  },
  {
    key: "preorder-commitment-test",
    name: "Pre-order / Commitment Test",
    category: "quantitative",
    summary: "Ask customers for a concrete commitment before the product is fully available.",
    bestFor: "Testing whether perceived value is strong enough for a real commitment.",
    effort: "Medium",
    evidenceStrength: "Strong",
    defaultDurationDays: 21,
  },
] as const;

export type ValidationMethod = (typeof validationMethods)[number];

export function getValidationMethod(key: string): ValidationMethod | undefined {
  return validationMethods.find((method) => method.key === key);
}